-- Inserting Math Questions
INSERT IGNORE INTO temp_questions (question_text, difficulty_level, category, hint, correct_answer, answer_option1, answer_option2, answer_option3, answer_option4)
VALUES
('What is 2 + 2?', 'easy', 'Math', 'Basic arithmetic', '4', '3', '4', '5', '6'),
('What is 3 * 3?', 'easy', 'Math', 'Multiplication', '9', '6', '7', '9', '10'),
('What is the square root of 16?', 'medium', 'Math', 'Square root calculation', '4', '2', '3', '4', '5'),
('Solve for x: 2x + 3 = 7', 'medium', 'Math', 'Simple algebra', '2', '1', '2', '3', '4'),
('Jazz is painting classrooms, and needs 9 liters of paint per room. If she has 108 liters of paint, how many rooms can she paint?', 'medium', 'Math', 'Divide the total liters of paint by the liters needed per room.', '12', '11', '12', '13', '14'),
('Noel is painting classrooms, and needs 11 liters of paint per room. If he has 132 liters of paint, how many rooms can he paint?', 'medium', 'Math', 'Divide the total liters of paint by the liters needed per room.', '12', '11', '12', '13', '14'),
('You have 36 eggs. How many dozen is that?', 'medium', 'Math', 'There are 12 eggs in a dozen.', '3', '3', '6', '9', '12'),
('The scale of a model of the planet Saturn is 1 : 200,000,000. If the actual diameter of Saturn is 116,000 km, what is the diameter of the model?', 'medium', 'Math', 'Divide the actual diameter by the scale factor.', '0.58', '0.58', '1.58', '2.58', '3.58'),
('The scale of a model of a mountain is 1 : 100,000. If the actual height of the mountain is 8,120 m, then what is the height of the model of the mountain?', 'medium', 'Math', 'Divide the actual height by the scale factor.', '81.2', '8.12', '81.2', '812', '0.812'),
('The distance between Ipswich and Johnsonville is 200 km, and the distance between them on a map is 4 cm. What is the scale of the map?', 'medium', 'Math', 'Divide the actual distance by the map distance.', '1:50,000', '1:50,000', '1:100,000', '1:200,000', '1:500,000'),
('The height of a tower is 600 m, and the height of a scale model of the tower is 30 cm. What is the scale of the model?', 'medium', 'Math', 'Divide the actual height by the model height.', '1:20', '1:20', '1:200', '1:2000', '1:20000'),
('The distance covered (d km) by a cyclist peddling at a constant rate is directly proportional to the time taken (t hours), and d = 150 when t = 7.5. What is the value of t when d = 110?', 'medium', 'Math', 'Set up a proportion based on the given information.', '5.5', '5', '5.5', '6', '6.5'),
('What is the integral of 2x dx?', 'hard', 'Math', 'Integration', 'x^2 + C', 'x + C', 'x^2 + C', '2x + C', 'x^2/2 + C'),
('What value does the 7 represent in the number 94.087?', 'medium', 'Math', 'Consider the place value of 7 in the number.', '0.7', '0.07', '7', '0.7', '7000'),
('X=47.3 - 8, X=?', 'medium', 'Math', 'Subtract 8 from 47.3.', '39.3', '39.3', '40.3', '41.3', '42.3'),
('Heather has eleven pencils. She buys another twenty-three pencils. Write the above as an addition number sentence with the correct answer.', 'medium', 'Math', 'Add the two numbers together.', '34', '33', '32', '34', '35'),
('Karl did a survey of the favorite colors of the students in his class. How many of the students did not like blue as their favorite color?', 'medium', 'Math', 'Count the occurrences of colors other than blue.', '12', '14', '10', '12', '16'),
('Tammy threw two cubical dice at the same time and added together the scores on their top faces. She did this 36 times. How many times was the sum of the scores on the two dice an odd number?', 'medium', 'Math', 'Consider the conditions under which two numbers add to an odd number.', '19', '17', '19', '21', '23'),
('A letter is chosen at random from the word PARALLELOGRAM. What is the set of possible outcomes?', 'medium', 'Math', 'Identify the unique letters in the word.', '{P, A, R, L, E, O, G, M}', '{P, A, R, L, E, O, G, M}', '{P, A, R, E, O, M}', '{P, R, E, G, M}', '{P, A, R, L, G, M}'),
('How many minutes is 1 day?', 'medium', 'Math', 'Multiply the number of hours by 60.', '1440', '1440', '1480', '1500', '1520'),
('Mason cut up each cake into 11 slices, and ended up with 121 slices altogether. How many cakes did he cut up?', 'medium', 'Math', 'Divide the total number of slices by the slices per cake.', '11', '11', '12', '13', '14'),
('Drew measured 96m using an 8m tape measure. How many times did he need to use the tape measure?', 'medium', 'Math', 'Divide the total distance by the length of the tape measure.', '12', '11', '12', '13', '14'),
('Find a solution of the Linear Diophantine Equation 200x + 54y = 21', 'hard', 'Math', 'Consider integer solutions that satisfy the equation.', 'No solution', 'x = 2, y = 1', 'x = -2, y = 1', 'x = 3, y = -1', 'x = 1, y = -2'),
('Find the general solution of the Linear Diophantine Equation 26x + 22y = 738', 'hard', 'Math', 'Use the Euclidean algorithm to solve for x and y.', 'x = 27, y = 3', 'x = 9, y = 0', 'x = -27, y = 15', 'x = 2, y = 16', 'x = 0, y = 33'),
('Find the general solution of the Linear Diophantine Equation 20x + 11y = 3', 'hard', 'Math', 'Use the Euclidean algorithm to solve for x and y.', 'x = -1, y = 1', 'x = 2, y = -3', 'x = 4, y = 5', 'x = 0, y = -1'),
('What is the value of π (pi) rounded to two decimal places?', 'easy', 'Math', 'It starts with 3.1.', '3.14', '3.14', '3.15', '3.16', '3.13'),
('What is the square root of 144?', 'easy', 'Math', 'It is a perfect square.', '12', '12', '14', '16', '10'),
('What is 15% of 200?', 'medium', 'Math', 'Find 15% of 200.', '30', '30', '25', '35', '40'),
('Solve for x: 2x + 3 = 11.', 'medium', 'Math', 'Isolate x.', '4', '4', '5', '3', '6'),
('What is the area of a triangle with a base of 8 cm and a height of 5 cm?', 'medium', 'Math', 'Use the formula: (1/2) * base * height.', '20 cm²', '20 cm²', '30 cm²', '40 cm²', '25 cm²'),
('What is the result of 7 cubed (7^3)?', 'medium', 'Math', '7 * 7 * 7.', '343', '343', '49', '2401', '147'),
('What is the perimeter of a square with a side length of 9 cm?', 'medium', 'Math', 'Perimeter of a square is 4 times the side length.', '36 cm', '36 cm', '81 cm', '45 cm', '27 cm'),
('Simplify: 4(3x + 2) = ?', 'medium', 'Math', 'Distribute the 4.', '12x + 8', '12x + 8', '12x + 2', '7x + 4', '3x + 8'),
('Convert 3/4 into a decimal.', 'easy', 'Math', 'It is 3 divided by 4.', '0.75', '0.75', '0.5', '0.25', '0.85'),
('If a car travels 60 miles in 1.5 hours, what is its average speed?', 'medium', 'Math', 'Use the formula: distance/time.', '40 mph', '40 mph', '45 mph', '50 mph', '60 mph'),
('Diana, Ed, and Fiona all shopped in the same store. Diana bought 2 apples, 3 bananas, and 1 coconut, and paid a total of $4.50. Ed bought 1 apple, 4 bananas, and 2 coconuts, and paid a total of $6.70. Fiona bought 3 apples, 1 banana, and 3 coconuts, and paid a total of $8.80. What was the cost of 1 coconut in this store?', 'hard', 'Math', 'Set up and solve a system of linear equations.', '$1.10', '$1.20', '$1.30', '$1.40');

-- Inserting Geography Questions
INSERT IGNORE INTO temp_questions (question_text, difficulty_level, category, hint, correct_answer, answer_option1, answer_option2, answer_option3, answer_option4)
VALUES
('What is the capital of France?', 'easy', 'Geography', 'Capital of a European country', 'Paris', 'London', 'Berlin', 'Paris', 'Rome'),
('Which continent is the Sahara Desert located on?', 'easy', 'Geography', 'Largest desert in the world', 'Africa', 'Asia', 'Africa', 'Australia', 'North America'),
('Which country has the longest coastline?', 'medium', 'Geography', 'Think about the largest countries', 'Canada', 'Russia', 'Australia', 'Canada', 'USA'),
('In which country is the Amazon rainforest located?', 'medium', 'Geography', 'Largest rainforest in the world', 'Brazil', 'Brazil', 'Peru', 'Colombia', 'Venezuela'),
('Which is the longest river in the world?', 'medium', 'Geography', 'It is located in Africa.', 'Nile', 'Nile', 'Amazon', 'Yangtze', 'Mississippi'),
('Mount Everest is located in which country?', 'medium', 'Geography', 'This country is located in South Asia.', 'Nepal', 'Nepal', 'India', 'China', 'Bhutan'),
('The Great Barrier Reef is located in which country?', 'medium', 'Geography', 'It is located in the Southern Hemisphere.', 'Australia', 'Australia', 'USA', 'Indonesia', 'Philippines'),
('Which is the largest desert in the world?', 'medium', 'Geography', 'It is located in Africa.', 'Sahara', 'Sahara', 'Arabian', 'Gobi', 'Kalahari'),
('What is the highest mountain in the world?', 'hard', 'Geography', 'It is located in Asia', 'Mount Everest', 'K2', 'Mount Everest', 'Kangchenjunga', 'Lhotse'),
('What is the smallest country in the world by area?', 'medium', 'Geography', 'It is located in Europe.', 'Vatican City', 'Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'),
('Which ocean is the largest in the world?', 'medium', 'Geography', 'It covers more than 30% of the Earth’s surface.', 'Pacific Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'),
('Which country is known as the Land of the Rising Sun?', 'easy', 'Geography', 'It is an island nation in East Asia.', 'Japan', 'Japan', 'China', 'South Korea', 'Thailand'),
('What is the most populous country in the world?', 'easy', 'Geography', 'It has over 1.4 billion people.', 'China', 'China', 'India', 'USA', 'Indonesia'),
('Which continent is the Amazon River located on?', 'easy', 'Geography', 'It is located in the Southern Hemisphere.', 'South America', 'South America', 'Africa', 'Asia', 'Australia'),
('What is the capital of Australia?', 'easy', 'Geography', 'It is not Sydney or Melbourne.', 'Canberra', 'Canberra', 'Sydney', 'Melbourne', 'Perth'),
('Which country is home to the ancient pyramids?', 'easy', 'Geography', 'It is located in Northern Africa.', 'Egypt', 'Egypt', 'Mexico', 'Peru', 'Sudan'),
('Which country is both in Europe and Asia?', 'medium', 'Geography', 'It is partially located in both continents.', 'Turkey', 'Turkey', 'Russia', 'Kazakhstan', 'Georgia'),
('What is the longest mountain range in the world?', 'medium', 'Geography', 'It runs along the western coast of South America.', 'Andes', 'Andes', 'Rockies', 'Himalayas', 'Alps'),
('Which sea is the saltiest body of water on Earth?', 'medium', 'Geography', 'It is located between Jordan and Israel.', 'Dead Sea', 'Dead Sea', 'Red Sea', 'Mediterranean Sea', 'Black Sea'),
('What is the second largest continent by land area?', 'easy', 'Geography', 'It is located south of Europe.', 'Africa', 'Africa', 'Asia', 'North America', 'South America'),
('What is the largest island in the world?', 'medium', 'Geography', 'It is located between the Arctic and Atlantic Oceans.', 'Greenland', 'Greenland', 'Australia', 'New Guinea', 'Borneo'),
('Which river runs through Paris?', 'easy', 'Geography', 'It is famous for boat tours and landmarks along its banks.', 'Seine', 'Seine', 'Thames', 'Danube', 'Rhine'),
('What is the hottest desert in the world?', 'medium', 'Geography', 'It is located in northern Africa.', 'Sahara', 'Sahara', 'Arabian', 'Kalahari', 'Sonoran'),
('Which city is known as "The Eternal City"?', 'easy', 'Geography', 'It is the capital of Italy.', 'Rome', 'Rome', 'Athens', 'Jerusalem', 'Cairo'),
('Which country has the most UNESCO World Heritage Sites?', 'hard', 'Geography', 'It is known for its rich cultural heritage.', 'Italy', 'Italy', 'China', 'Spain', 'Germany'),
('Which is the smallest ocean in the world?', 'hard', 'Geography', 'It surrounds the North Pole.', 'Arctic Ocean', 'Arctic Ocean', 'Indian Ocean', 'Southern Ocean', 'Atlantic Ocean'),
('Which country has the highest number of active volcanoes?', 'hard', 'Geography', 'It is an archipelago in Southeast Asia.', 'Indonesia', 'Indonesia', 'Japan', 'USA', 'Russia'),
('What is the largest non-polar desert in the world?', 'hard', 'Geography', 'It is located in Africa.', 'Sahara', 'Sahara', 'Arabian', 'Gobi', 'Kalahari'),
('Which European city is home to the headquarters of the European Union?', 'hard', 'Geography', 'It is the capital of Belgium.', 'Brussels', 'Brussels', 'Paris', 'Berlin', 'Amsterdam'),
('Which country is known as the "Land of a Thousand Lakes"?', 'hard', 'Geography', 'It is located in Northern Europe.', 'Finland', 'Finland', 'Canada', 'Norway', 'Sweden'),
('What is the deepest point in Earth\'s oceans?', 'hard', 'Geography', 'It is located in the western Pacific Ocean.', 'Mariana Trench', 'Mariana Trench', 'Tonga Trench', 'Philippine Trench', 'Puerto Rico Trench'),
('Which country has the highest average altitude?', 'hard', 'Geography', 'It is a landlocked country in South Asia.', 'Bhutan', 'Bhutan', 'Nepal', 'Switzerland', 'Bolivia'),
('What is the longest river in Europe?', 'hard', 'Geography', 'It flows through Russia.', 'Volga', 'Volga', 'Danube', 'Rhine', 'Ural'),
('Which African country was never colonized?', 'hard', 'Geography', 'It is one of the oldest countries in Africa.', 'Ethiopia', 'Ethiopia', 'Liberia', 'Ghana', 'Nigeria');


-- Inserting History Questions
INSERT IGNORE INTO temp_questions (question_text, difficulty_level, category, hint, correct_answer, answer_option1, answer_option2, answer_option3, answer_option4)
VALUES
('Who was the first President of the United States?', 'easy', 'History', 'American Revolution leader', 'George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'John Adams'),
('In which year did World War I begin?', 'easy', 'History', 'Early 20th century', '1914', '1912', '1914', '1916', '1918'),
('Who was the first man to step on the moon?', 'medium', 'History', 'Apollo 11 mission', 'Neil Armstrong', 'Buzz Aldrin', 'Neil Armstrong', 'Michael Collins', 'Yuri Gagarin'),
('What was the ancient Egyptian writing system called?', 'medium', 'History', 'Used in pyramids and tombs', 'Hieroglyphics', 'Hieroglyphics', 'Cuneiform', 'Latin', 'Sanskrit'),
('Who was the first President of the United States?', 'easy', 'History', 'He is on the one-dollar bill.', 'George Washington', 'George Washington', 'Thomas Jefferson', 'John Adams', 'James Madison'),
('Which empire was known as the "Empire on which the sun never sets"?', 'medium', 'History', 'It had colonies around the world.', 'British Empire', 'British Empire', 'Roman Empire', 'Ottoman Empire', 'Mongol Empire'),
('In what year did the Titanic sink?', 'medium', 'History', 'It hit an iceberg.', '1912', '1912', '1905', '1915', '1920'),
('Who was the first woman to fly solo across the Atlantic Ocean?', 'medium', 'History', 'She disappeared during a flight in 1937.', 'Amelia Earhart', 'Amelia Earhart', 'Harriet Quimby', 'Bessie Coleman', 'Jacqueline Cochran'),
('What was the main cause of the American Civil War?', 'medium', 'History', 'It was a conflict over a fundamental human right.', 'Slavery', 'Slavery', 'Taxes', 'Independence', 'Religion'),
('Who was the leader of the Soviet Union during World War II?', 'medium', 'History', 'He ruled with an iron fist.', 'Joseph Stalin', 'Joseph Stalin', 'Vladimir Lenin', 'Nikita Khrushchev', 'Leon Trotsky'),
('In which year did the Berlin Wall fall?', 'medium', 'History', 'It marked the end of the Cold War era.', '1989', '1989', '1975', '1991', '1985'),
('What was the name of the ship that brought the Pilgrims to America in 1620?', 'easy', 'History', 'It was one of the most famous ships in American history.', 'Mayflower', 'Mayflower', 'Santa Maria', 'Pinta', 'Nina'),
('Who was the first Emperor of Rome?', 'hard', 'History', 'He was the adopted son of Julius Caesar.', 'Augustus', 'Augustus', 'Julius Caesar', 'Nero', 'Caligula'),
('Which country was the first to land a man on the moon?', 'easy', 'History', 'It happened in 1969.', 'USA', 'USA', 'Russia', 'China', 'France'),
('Which empire was known as the "Land of the Rising Sun"?', 'hard', 'History', 'An East Asian empire', 'Japan', 'China', 'Japan', 'Korea', 'Vietnam'),
('Who was the first person to circumnavigate the globe?', 'hard', 'History', 'He was a Portuguese explorer.', 'Ferdinand Magellan', 'Ferdinand Magellan', 'Christopher Columbus', 'James Cook', 'Vasco da Gama'),
('What event started World War I?', 'hard', 'History', 'It happened in Sarajevo.', 'Assassination of Archduke Franz Ferdinand', 'Assassination of Archduke Franz Ferdinand', 'Invasion of Poland', 'Sinking of the Lusitania', 'Attack on Pearl Harbor'),
('Which dynasty built the Great Wall of China?', 'hard', 'History', 'It was built to protect against invasions from the north.', 'Qin Dynasty', 'Qin Dynasty', 'Ming Dynasty', 'Han Dynasty', 'Tang Dynasty'),
('Who was the British Prime Minister during most of World War II?', 'medium', 'History', 'He is famous for his leadership during the Blitz.', 'Winston Churchill', 'Winston Churchill', 'Neville Chamberlain', 'Clement Attlee', 'Stanley Baldwin'),
('What was the name of the ship that carried the first English settlers to Jamestown in 1607?', 'hard', 'History', 'It was one of three ships that made the journey.', 'Susan Constant', 'Susan Constant', 'Mayflower', 'Godspeed', 'Discovery'),
('Who was the last Czar of Russia?', 'medium', 'History', 'He was executed with his family during the Russian Revolution.', 'Nicholas II', 'Nicholas II', 'Alexander III', 'Peter the Great', 'Ivan the Terrible'),
('What was the main objective of the Manhattan Project?', 'medium', 'History', 'It was a top-secret military project during World War II.', 'Develop the atomic bomb', 'Develop the atomic bomb', 'Build a space shuttle', 'Create the internet', 'Develop nuclear submarines'),
('Which treaty ended World War I?', 'hard', 'History', 'It was signed in 1919.', 'Treaty of Versailles', 'Treaty of Versailles', 'Treaty of Paris', 'Treaty of Ghent', 'Treaty of Tordesillas'),
('Who led the Haitian Revolution?', 'hard', 'History', 'He was a former slave who became a military leader.', 'Toussaint Louverture', 'Toussaint Louverture', 'Simon Bolivar', 'Che Guevara', 'Jean-Jacques Dessalines'),
('Which civilization built the pyramids?', 'Egyptians', 'Egyptians', 'Mayans', 'Romans', 'Greeks'),
('What was the capital of the Roman Empire?', 'Rome', 'Rome', 'Athens', 'Constantinople', 'Alexandria'),
('Who was the first emperor of China?', 'Qin Shi Huang', 'Qin Shi Huang', 'Liu Bang', 'Sun Yat-sen', 'Mao Zedong'),
('Which ancient civilization is known for developing cuneiform script?', 'Sumerians', 'Sumerians', 'Egyptians', 'Babylonians', 'Phoenicians'),
('In what year did World War I begin?', '1914', '1914', '1915', '1916', '1917'),
('Which country was invaded to start World War II?', 'Poland', 'Poland', 'France', 'Belgium', 'Austria'),
('Who was the Prime Minister of the United Kingdom during most of World War II?', 'Winston Churchill', 'Winston Churchill', 'Neville Chamberlain', 'Clement Attlee', 'Stanley Baldwin'),
('Which two cities were the atomic bombs dropped on in Japan during World War II?', 'Hiroshima and Nagasaki', 'Hiroshima and Nagasaki', 'Tokyo and Osaka', 'Kyoto and Yokohama', 'Sapporo and Fukuoka'),
('Who wrote the Declaration of Independence?', 'Thomas Jefferson', 'Thomas Jefferson', 'George Washington', 'Benjamin Franklin', 'John Adams'),
('What year was the United States Constitution ratified?', '1788', '1788', '1776', '1791', '1800'),
('Who was the U.S. president during the Civil War?', 'Abraham Lincoln', 'Abraham Lincoln', 'Ulysses S. Grant', 'Jefferson Davis', 'Andrew Jackson'),
('What was the last state to join the United States?', 'Hawaii', 'Hawaii', 'Alaska', 'Arizona', 'New Mexico'),
('What year did the Berlin Wall go up?', 'medium', 'History', 'It separated East and West Berlin.', '1961', '1961', '1945', '1970', '1955');

-- Inserting Science Questions
INSERT IGNORE INTO temp_questions (question_text, difficulty_level, category, hint, correct_answer, answer_option1, answer_option2, answer_option3, answer_option4)
VALUES
('What is the chemical symbol for water?', 'easy', 'Science', 'Two hydrogen atoms and one oxygen atom', 'H2O', 'H2', 'H2O', 'O2', 'HO2'),
('What planet is known as the Red Planet?', 'easy', 'Science', 'Fourth planet from the Sun', 'Mars', 'Venus', 'Mars', 'Jupiter', 'Saturn'),
('What is the speed of light?', 'medium', 'Science', 'Measured in meters per second', '299,792,458 m/s', '299,792 m/s', '299,792,458 m/s', '300,000,000 m/s', '150,000,000 m/s'),
('What is the powerhouse of the cell?', 'medium', 'Science', 'Produces energy', 'Mitochondria', 'Nucleus', 'Mitochondria', 'Ribosome', 'Chloroplast'),
('What is the chemical symbol for gold?', 'easy', 'Science', 'It is used in jewelry and electronics.', 'Au', 'Au', 'Ag', 'Pb', 'Hg'),
('Which organ in the human body is primarily responsible for filtering blood?', 'medium', 'Science', 'There are two of these organs.', 'Kidney', 'Kidney', 'Liver', 'Heart', 'Lungs'),
('What is the main gas found in the air we breathe?', 'easy', 'Science', 'It makes up about 78% of the air.', 'Nitrogen', 'Nitrogen', 'Oxygen', 'Carbon Dioxide', 'Hydrogen'),
('What is the boiling point of water at sea level?', 'medium', 'Science', 'It is measured in degrees Celsius.', '100°C', '100°C', '0°C', '50°C', '212°F'),
('Which planet is closest to the Sun?', 'easy', 'Science', 'It is the smallest planet in our solar system.', 'Mercury', 'Mercury', 'Venus', 'Earth', 'Mars'),
('What is the most common element in the universe?', 'medium', 'Science', 'It is the lightest element.', 'Hydrogen', 'Hydrogen', 'Helium', 'Oxygen', 'Carbon'),
('Which part of the cell contains genetic material?', 'medium', 'Science', 'It is the control center of the cell.', 'Nucleus', 'Nucleus', 'Cytoplasm', 'Mitochondria', 'Cell Membrane'),
('What is the name of the process plants use to convert sunlight into food?', 'medium', 'Science', 'It occurs in the chloroplasts.', 'Photosynthesis', 'Photosynthesis', 'Respiration', 'Transpiration', 'Germination'),
('Who developed the theory of relativity?', 'medium', 'Science', 'He is one of the most famous physicists in history.', 'Albert Einstein', 'Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'),
('What type of bond involves the sharing of electron pairs between atoms?', 'hard', 'Science', 'It is the strongest type of chemical bond.', 'Covalent', 'Covalent', 'Ionic', 'Hydrogen', 'Metallic'),
('What is the most abundant gas in the Earth’s atmosphere?', 'hard', 'Science', 'Makes up around 78%', 'Nitrogen', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Argon'),
('What is the atomic number of carbon?', 'medium', 'Science', 'It is essential for life on Earth.', '6', '6', '8', '12', '14'),
('Which element is known as the "King of Chemicals"?', 'hard', 'Science', 'It is the most widely produced chemical in the world.', 'Sulfuric acid', 'Sulfuric acid', 'Hydrochloric acid', 'Nitric acid', 'Acetic acid'),
('What is the main component of the sun?', 'easy', 'Science', 'It is the most abundant element in the universe.', 'Hydrogen', 'Hydrogen', 'Helium', 'Carbon', 'Oxygen'),
('Which planet has the most moons?', 'medium', 'Science', 'It is the largest planet in our solar system.', 'Jupiter', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'),
('What is the name of the force that causes objects to fall to the ground?', 'easy', 'Science', 'It is a fundamental force of nature.', 'Gravity', 'Gravity', 'Magnetism', 'Electromagnetism', 'Friction'),
('Which scientist is known for the laws of motion?', 'medium', 'Science', 'He is one of the most influential scientists of all time.', 'Isaac Newton', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla'),
('What is the most abundant metal in the Earth\'s crust?', 'hard', 'Science', 'It is commonly used in making cans and foil.', 'Aluminum', 'Aluminum', 'Iron', 'Calcium', 'Magnesium'),
('What is the hardest natural substance on Earth?', 'medium', 'Science', 'It is often used in cutting tools.', 'Diamond', 'Diamond', 'Quartz', 'Corundum', 'Topaz'),
('Which part of the human brain controls movement and balance?', 'medium', 'Science', 'It is located at the back of the brain.', 'Cerebellum', 'Cerebellum', 'Cerebrum', 'Brainstem', 'Thalamus'),
('What is the pH level of pure water?', 'easy', 'Science', 'It is neutral.', '7', '7', '1', '4', '10'),
('What type of macromolecule are enzymes?', 'medium', 'Science', 'They are biological catalysts.', 'Proteins', 'Proteins', 'Carbohydrates', 'Lipids', 'Nucleic Acids'),
('What is the most abundant element in the Earth\'s atmosphere?', 'easy', 'Science', 'It makes up about 78% of the air.', 'Nitrogen', 'Nitrogen', 'Oxygen', 'Carbon Dioxide', 'Argon'),
('Which part of the cell is responsible for energy production?', 'medium', 'Science', 'It is known as the powerhouse of the cell.', 'Mitochondria', 'Mitochondria', 'Nucleus', 'Ribosome', 'Golgi Apparatus'),
('What is the chemical symbol for sodium?', 'easy', 'Science', 'It is an alkali metal.', 'Na', 'Na', 'S', 'Cl', 'K'),
('What process do plants use to make food?', 'easy', 'Science', 'It occurs in the chloroplasts.', 'Photosynthesis', 'Photosynthesis', 'Respiration', 'Fermentation', 'Transpiration'),
('What is the largest organ in the human body?', 'easy', 'Science', 'It covers the entire body.', 'Skin', 'Skin', 'Liver', 'Heart', 'Brain'),
('What planet is closest to Earth?', 'medium', 'Science', 'It is often called Earth\'s twin.', 'Venus', 'Venus', 'Mars', 'Mercury', 'Jupiter'),
('Which gas is essential for human respiration?', 'easy', 'Science', 'It is needed for breathing.', 'Oxygen', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'),
('What is the main function of red blood cells?', 'medium', 'Science', 'They carry a vital substance throughout the body.', 'Transport oxygen', 'Transport oxygen', 'Fight infections', 'Clot blood', 'Produce antibodies'),
('What is the primary source of energy for life on Earth?', 'easy', 'Science', 'It is a star.', 'The Sun', 'The Sun', 'The Moon', 'The Earth’s core', 'Fossil fuels');
