-- Inserting Math Questions
INSERT INTO temp_questions (question_text, difficulty_level, category, hint, correct_answer, answer_option1, answer_option2, answer_option3, answer_option4)
VALUES
('What is 2 + 2?', 'easy', 'Math', 'Basic arithmetic', '4', '3', '4', '5', '6'),
('What is 3 * 3?', 'easy', 'Math', 'Multiplication', '9', '6', '7', '9', '10'),
('What is the square root of 16?', 'medium', 'Math', 'Square root calculation', '4', '2', '3', '4', '5'),
('Solve for x: 2x + 3 = 7', 'medium', 'Math', 'Simple algebra', '2', '1', '2', '3', '4'),
('Jazz is painting classrooms, and needs 9 liters of paint per room. If she has 108 liters of paint, how many rooms can she paint?', 'medium', 'Math', 'Divide the total liters of paint by the liters needed per room.', '12', '11', '12', '13', '14'),
('Noel is painting classrooms, and needs 11 liters of paint per room. If he has 132 liters of paint, how many rooms can he paint?', 'medium', 'Math', 'Divide the total liters of paint by the liters needed per room.', '12', '11', '12', '13', '14'),
('You have 36 eggs. How many dozen is that?', 'medium', 'Math', 'There are 12 eggs in a dozen.', '3', '3', '6', '9', '12'),
('The scale of a model of the planet Saturn is 1 : 200,000,000. If the actual diameter of Saturn is 116,000 km, what is the diameter of the model?', 'medium', 'Math', 'Divide the actual diameter by the scale factor.', '0.58', '0.58', '1.58', '2.58', '3.58'),
('The scale of a model of a mountain is 1 : 100,000. If the actual height of the mountain is 8,120 m, then what is the height of the model of the mountain?', 'medium', 'Math', 'Divide the actual height by the scale factor.', '81.2', '8.12', '81.2', '812', '0.812'),
('The distance between Ipswich and Johnsonville is 200 km, and the distance between them on a map is 4 cm. What is the scale of the map?', 'medium', 'Math', 'Divide the actual distance by the map distance.', '1:50,000', '1:50,000', '1:100,000', '1:200,000', '1:500,000'),
('The height of a tower is 600 m, and the height of a scale model of the tower is 30 cm. What is the scale of the model?', 'medium', 'Math', 'Divide the actual height by the model height.', '1:20', '1:20', '1:200', '1:2000', '1:20000'),
('The distance covered (d km) by a cyclist peddling at a constant rate is directly proportional to the time taken (t hours), and d = 150 when t = 7.5. What is the value of t when d = 110?', 'medium', 'Math', 'Set up a proportion based on the given information.', '5.5', '5', '5.5', '6', '6.5'),
('What is the integral of 2x dx?', 'hard', 'Math', 'Integration', 'x^2 + C', 'x + C', 'x^2 + C', '2x + C', 'x^2/2 + C'),
('What value does the 7 represent in the number 94.087?', 'medium', 'Math', 'Consider the place value of 7 in the number.', '0.7', '0.07', '7', '0.7', '7000'),
('X=47.3 - 8, X=?', 'medium', 'Math', 'Subtract 8 from 47.3.', '39.3', '39.3', '40.3', '41.3', '42.3'),
('Heather has eleven pencils. She buys another twenty-three pencils. Write the above as an addition number sentence with the correct answer.', 'medium', 'Math', 'Add the two numbers together.', '34', '33', '32', '34', '35'),
('Karl did a survey of the favorite colors of the students in his class. How many of the students did not like blue as their favorite color?', 'medium', 'Math', 'Count the occurrences of colors other than blue.', '12', '14', '10', '12', '16'),
('A letter is chosen at random from the word PARALLELOGRAM. What is the set of possible outcomes?', 'medium', 'Math', 'Identify the unique letters in the word.', '{P, A, R, L, E, O, G, M}', '{P, A, R, L, E, O, G, M}', '{P, A, R, E, O, M}', '{P, R, E, G, M}', '{P, A, R, L, G, M}'),
('How many minutes is 1 day?', 'medium', 'Math', 'Multiply the number of hours by 60.', '1440', '1440', '1480', '1500', '1520'),
('Mason cut up each cake into 11 slices, and ended up with 121 slices altogether. How many cakes did he cut up?', 'medium', 'Math', 'Divide the total number of slices by the slices per cake.', '11', '11', '12', '13', '14'),
('Drew measured 96m using an 8m tape measure. How many times did he need to use the tape measure?', 'medium', 'Math', 'Divide the total distance by the length of the tape measure.', '12', '11', '12', '13', '14'),
('Find a solution of the Linear Diophantine Equation 200x + 54y = 21', 'hard', 'Math', 'Consider integer solutions that satisfy the equation.', 'No solution', 'x = 2, y = 1', 'x = -2, y = 1', 'x = 3, y = -1', 'x = 1, y = -2'),
('Find the general solution of the Linear Diophantine Equation 26x + 22y = 738', 'hard', 'Math', 'Use the Euclidean algorithm to solve for x and y.', 'x = 27, y = 3', 'x = 9, y = 0', 'x = -27, y = 15', 'x = 2, y = 16', 'x = 0, y = 33'),
('Find the general solution of the Linear Diophantine Equation 21x + 15y = 261', 'hard', 'Math', 'Use the Euclidean algorithm to solve for x and y.', 'x = 9, y = 6', 'x = -3, y = 19', 'x = 5, y = 12', 'x = 6, y = 3'),
('Find the general solution of the Linear Diophantine Equation 20x + 11y = 3', 'hard', 'Math', 'Use the Euclidean algorithm to solve for x and y.', 'x = -1, y = 1', 'x = 2, y = -3', 'x = 4, y = 5', 'x = 0, y = -1'),
('What is the value of π (pi) rounded to two decimal places?', 'easy', 'Math', 'It starts with 3.1.', '3.14', '3.14', '3.15', '3.16', '3.13'),
('What is the square root of 144?', 'easy', 'Math', 'It is a perfect square.', '12', '12', '14', '16', '10'),
('What is 15% of 200?', 'medium', 'Math', 'Find 15% of 200.', '30', '30', '25', '35', '40'),
('Tammy threw two cubical dice at the same time and added together the scores on their top faces. She did this 36 times. How many times was the sum of the scores on the two dice an odd number?', 'medium', 'Math', 'Consider the conditions under which two numbers add to an odd number.', '19', '17', '19', '21', '23');
